---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2024/5/21 18:31
---
local voucherId = ARVG[1]
local userId = ARVG[2]
local orderId = ARVG[3]

local stockKey = 'seckill:stock' .. voucherId
local orderKey = 'seckill:order' .. voucherId

if (tonumber(redis.call('get', stockKey) <= 0)) then
    return 1
end
if (redis.call('sismember', orderKey, userId) == 1) then
    return 2
end
redis.call('incrby', stockKey, -1)
redis.call('sadd', orderKey, userId)
-- 发送消息到阻塞队列当中
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)
return 0