---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2024/5/20 21:59
---

local key = KEYS[1]
local threadId = ARGV[1]

local id = redis.call('get', key)
if (id == threadId) then
    return redis.call('del', key)
end
return 0